rapids:
  calcite:
    mode: standard
    standard:
      properties:
        model : /model/model.json
        quoting : DOUBLE_QUOTE
        caseSensitive : true
  services:
    jdbc:
      enabled : true
      port : 18200
      protocol: json