image: docker-ci.qpointz.io/ci-gradle-graalvm:$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
stages:
  - init
  - test
  - build
  - package

docker:buildImages:
  stage: init
  image: docker:latest
  script:
    - echo "$NEXUS_PASSWORD" | docker login $DOCKER_REPO_CI  -u $NEXUS_USER --password-stdin
    - docker build etc/docker/ci-graalvm -t docker-ci.qpointz.io/ci-gradle-graalvm:$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG
    - docker push docker-ci.qpointz.io/ci-gradle-graalvm:$CI_PROJECT_PATH_SLUG-$CI_COMMIT_REF_SLUG

runTests:
  stage: test
  script:
    - gradle testCodeCoverageReport
  artifacts:
    reports:
      junit: ./**/*/build/test-results/test/*.xml
    paths:
      - ./**/*/build/reports/jacoco/testCodeCoverageReport/*.xml

runTestsIT:
  stage: test
  script:
    - gradle testITCodeCoverageReport
  artifacts:
    reports:
      junit: ./**/*/build/test-results/testIT/*.xml
    paths:
      - ./**/*/build/reports/jacoco/testITCodeCoverageReport/*.xml

buildJDBCDriver:
  stage: build
  script:
    - gradle shadowJar
  artifacts:
    paths:
      - ./rapids-jdbc-driver/build/libs/*-all.jar

buildRapidsApp:
  stage: build
  script:
    - gradle :rapids-srv-worker:bootstrapApp
  artifacts:
    paths:
      - ./rapids-srv-worker/build/rapids-app/*/*

buildRapidsDocker:
  stage: package
  dependencies:
    - buildRapidsApp
  image: docker:latest
  script:
    - echo "$NEXUS_PASSWORD" | docker login $DOCKER_REPO_CI  -u $NEXUS_USER --password-stdin
    - docker build -f ./rapids-srv-worker/src/main/docker/Dockerfile.jvm -t docker-ci.qpointz.io/rapids:$CI_COMMIT_REF_SLUG .
    - docker push docker-ci.qpointz.io/rapids:$CI_COMMIT_REF_SLUG