apiVersion: v1
kind: Service
metadata:
  name: worker-jdbc-service
spec:
  type: NodePort
  selector:
    app: srv-worker
  ports:
  - name: jdbc-service-port
    protocol: TCP
    port: 18200
    targetPort: jdbc-port
    nodePort: 30820
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: srv-worker-deployment
  labels:
    app: srv-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: srv-worker
  template:
    metadata:
      name: srv-worker
      labels:
        app: srv-worker
    spec:
      containers:
        - name: worker
          image: qpointz/rapids-worker:feat-k8s-deployment
          ports:
            - name: odata-port 
              containerPort: 18080
            - name: jdbc-port
              containerPort: 18200
          env:
            - name: RAPIDS_APPLICATION_CONFIG_ADDITIONAL_DIR
              value: "/config"
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
      volumes:
        - name: config
          configMap:
            name: srv-worker-app-properties
            items:
              - key: "application.yaml"
                path: "application.yaml"
              - key: "model.json"
                path: "model.json"