rapids:
  calcite:
    mode: standard
    standard:
      properties:
        model : ./rapids-srv-worker/config/model.json
        quoting : DOUBLE_QUOTE
        caseSensitive : true
  services:
    jdbc:
      enabled : true
      port : 18200
      protocol: json
    odata:
      enabled : true
      port : 18080
      namespace : "io.qpointz.test"