qpointz:
  rapids:
    calcite:
      mode: standard
      standard:
        properties:
          - "model=etc/example/model.json"
          - "quoting=BACK_TICK"
    services:
      jdbc:
        enabled: true
        worker:
          name: jdbc-service-worker-pool
          pool-size : 10
        port: 18200
        protocol: json
      flight:
        enabled: true
        worker:
          name: flight-grpc-worker-pool
          pool-size: 10
        host: localhost
        port: 18300
      ftp:
        enabled: true
        worker:
          name: flight-ftp-worker-pool
          pool-size: 10
        host: localhost
        port: 18220